name: Deploy ML App to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: aws-edge-app
          IMAGE_TAG: latest
        run: |
          # Білд та пуш
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update AWS Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ml-edge-inference \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/aws-edge-app:latest

      - name: Update Selector Lambda
        run: |
          aws lambda update-function-code \
            --function-name ml-data-selector \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/aws-edge-app:latest
